// AUTO-GENERATED BY scripts/sync-ipc-types.js - DO NOT EDIT MANUALLY
/* eslint-disable @typescript-eslint/no-explicit-any */

type Awaitable<T> = T extends Promise<infer R> ? Promise<R> : Promise<T>;
type ToRendererMethod<T> = T extends { _isEvent: true }
  ? (listener: (payload: Parameters<T>[0]) => void) => () => void
  : (...args: Parameters<T>) => Awaitable<ReturnType<T>>;

type IpcModules = {
  config: {
    get: typeof import('../main/ipc/config/get.ipc').default;
    onThemeUpdate: typeof import('../main/ipc/config/onThemeUpdate.ipc').default;
    save: typeof import('../main/ipc/config/save.ipc').default;
  };
  system: {
    bootloading: typeof import('../main/ipc/system/bootloading.ipc').default;
    getAppInfo: typeof import('../main/ipc/system/getAppInfo.ipc').default;
    getBootloadProgressing: typeof import('../main/ipc/system/getBootloadProgressing.ipc').default;
    reloadHotkeys: typeof import('../main/ipc/system/reloadHotkeys.ipc').default;
  };
  update: {
    check: typeof import('../main/ipc/update/check.ipc').default;
    getState: typeof import('../main/ipc/update/getState.ipc').default;
    install: typeof import('../main/ipc/update/install.ipc').default;
    onStatusChange: typeof import('../main/ipc/update/onStatusChange.ipc').default;
  };
  window: {
    close: typeof import('../main/ipc/window/close.ipc').default;
    hide: typeof import('../main/ipc/window/hide.ipc').default;
    maximize: typeof import('../main/ipc/window/maximize.ipc').default;
    minimize: typeof import('../main/ipc/window/minimize.ipc').default;
    onShow: typeof import('../main/ipc/window/onShow.ipc').default;
    openUpdate: typeof import('../main/ipc/window/openUpdate.ipc').default;
  };
};

type RendererApi<T> = {
  [M in keyof T]: {
    [K in keyof T[M]]: ToRendererMethod<T[M][K]>;
  };
};

export type GeneratedElectronApi = RendererApi<IpcModules>;

declare global {
  interface Window {
    electron: GeneratedElectronApi;
  }
}

export {};
